swarmalator:
  dimension: 3  # Spatial and phase dimensions
  num_agents: 100  # Number of swarmalators
  alpha: 1  # Exponent for spatial attraction
  beta: 3  # Exponent for spatial repulsion
  gamma: 1  # Exponent for phase coupling
  J: 0.8  # Phase attraction parameter, between -1 and 1
  R: 0  # Vision radius, between 0 and 2
  epsilon_a: 0.5  # Attractive phase coupling strength
  epsilon_r: 0.5  # Repulsive phase coupling strength
  noise_strength:
    position: 0.01  # Noise in position update
    orientation: 0.01  # Noise in orientation update
  initial_conditions:
    position_range: [-1, 1]  # Initial positions drawn from a box [-1,1] in each dimension
    theta_range: [0, 3.1416]  # Initial polar angles
    phi_range: [0, 6.2832]  # Initial azimuthal angles
  integration:
    method: "RK4"  # Runge-Kutta 4th order integration
    timestep: 0.1  # Integration step size
  velocity:
    self_propelled: False  # Whether agents have self-propelled motion
    magnitude: 0.0  # Velocity magnitude if self-propelled
