# repo: https://github.com/astral-sh/ruff
#   rev: v0.3.5  # Use the latest stable version
#   hooks:
#     - id: ruff
#     - id: ruff-format

repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest stable version
    hooks:
      - id: black
