ode_solver:
  # The ODE solver to use for the simulation.
  # Options: 'RK45', 'RK23', 'DOP853', 'Radau', 'BDF', 'LSODA', 'Dopri5'
  solver: 'Dopri5'
  time:
    t0: 0.0  # Initial time
    t1: 30.0  # Final time
    dt: 0.01  # Time step for integration
  saveat:
    t0: 0.0  # Time to save the first state
    t1: 30.0  # Time to save the last state
    dt: 0.1  # Time step for saving states